podAnnotations:
  pod-security.kubernetes.io/enforce: privileged
promtail:
  fullnameOverride: promtail
  config:
    logLevel: info
    clients:
      - url: http://loki-headless.kube-monitoring.svc.cluster.local:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true
