ingress:
  enabled: true
  hosts:
    - monitoring.nidr0x.win
  annotations:
    cert-manager.io/cluster-issuer: zerossl-prod
    external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
  paths:
    - /victoriametrics
  pathType: Prefix
  tls:
    - hosts:
        - monitoring.nidr0x.win

persistence:
  enabled: true
  storageClass: proxmox-k8s-zfs
  size: 10Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 1Gi
    cpu: 500m

service:
  type: ClusterIP
  port: 8428

securityContext:
  runAsUser: 1001
  runAsGroup: 1001
  fsGroup: 1001

# Additional configuration
extraArgs:
  - --http.pathPrefix=/victoriametrics
  - --retentionPeriod=7d
