apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-apps-yaml
spec:
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: everest
      source:
        repoURL: https://github.com/nidr0x/k8s-gitops
        path: argocd/apps/
        targetRevision: "{{targetRevision}}"
      destination:
        namespace: argocd
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
