apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-nidr0x-win
spec:
  secretName: prod-cert-zerossl
  issuerRef:
    kind: ClusterIssuer
    name: zerossl-prod
  duration: 2160h0m0s # 90d
  renewBefore: 720h0m0s # 30d before SSL will expire, renew it
  commonName: "*.nidr0x.win"
  dnsNames:
    - "nidr0x.win"
    - "*.nidr0x.win"
