apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: transmission
resources:
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - http-route.yaml
  - network-policies.yaml
  - service.yaml
