fail_fast: false
repos:
  - repo: https://github.com/onedr0p/sops-pre-commit
    rev: v2.1.0
    hooks:
      - id: forbid-secrets
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.4
    hooks:
      - id: gitleaks
