---
version: "3"

vars:
  CLUSTER: '{{.CLUSTER | default "main"}}'
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}"

includes:
  pre-commit:
    taskfile: .taskfiles/pre-commit
    dir: .taskfiles/pre-commit
  talos:
    taskfile: .taskfiles/talos
    dir: .taskfiles/talos
  kubernetes:
    taskfile: .taskfiles/kubernetes
    dir: .taskfiles/kubernetes

tasks:
  default:
    silent: true
    cmds:
      - task -l
