apiVersion: batch/v1
kind: CronJob
metadata:
  name: cloudflare-ddns
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 100
  suspend: false
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 100
      template:
        spec:
          containers:
            - name: cloudflare-ddns
              image: ghcr.io/nidr0x/cloudflare-ddns-updater:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                runAsNonRoot: true
                runAsUser: 82
                allowPrivilegeEscalation: false
                runAsGroup: 82
              resources:
                requests:
                  cpu: 50m
                  memory: 32Mi
                limits:
                  memory: 64Mi
              envFrom:
              env:
                - name: CLOUDFLARE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-ddns
                      key: CLOUDFLARE_API_TOKEN
                - name: CLOUDFLARE_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: cloudflare-ddns
                      key: CLOUDFLARE_EMAIL
          restartPolicy: OnFailure
