apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: cloudflare-ddns

  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CF_API_TOKEN
    - secretKey: CLOUDFLARE_EMAIL
      remoteRef:
        key: CF_API_EMAIL
