apiVersion: v1
kind: PersistentVolume
metadata:
  name: homebridge-config-pv
spec:
  capacity:
    storage: 768Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: homebridge-config
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/homebridge/config
