apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-database
  namespace: kube-monitoring
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.6-bookworm

  bootstrap:
    initdb:
      database: grafana
      owner: grafana

  postgresql:
    parameters:
      max_wal_size: "512MB"
      min_wal_size: "128MB"
      archive_timeout: "10min"
      checkpoint_timeout: "15min"
      checkpoint_completion_target: "0.9"
      wal_keep_size: "256MB"

  backup:
    barmanObjectStore:
      destinationPath: s3://nidr0x-homelab-backups/cloudnative-pg
      endpointURL: https://de6356c843cfe00a0c3ff3b669892ca9.r2.cloudflarestorage.com
      serverName: grafana-database-v2
      s3Credentials:
        accessKeyId:
          name: victoriametricsstack-oauth2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: victoriametricsstack-oauth2
          key: SECRET_ACCESS_KEY
      data:
        compression: bzip2
        encryption: AES256
      wal:
        compression: bzip2
        maxParallel: 4
        encryption: AES256
    retentionPolicy: "7d"

  logLevel: info
  primaryUpdateStrategy: unsupervised

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 27Gi
      storageClassName: proxmox-k8s-zfs

  walStorage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
      storageClassName: proxmox-k8s-zfs

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: grafana
  namespace: kube-monitoring
spec:
  cluster:
    name: grafana-database
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-backup
  namespace: kube-monitoring
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: grafana-database
