crds:
  enabled: true

victoria-metrics-operator:
  enabled: true
  operator:
    disable_prometheus_converter: false
    enable_converter_ownership: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      memory: 100Mi

grafana:
  enabled: true
  defaultDashboardsTimezone: Europe/Madrid
  envFromSecrets:
    - name: victoriametricsstack-oauth2
    - name: grafana-database-app
  ingress:
    enabled: true
    hosts:
      - monitoring.nidr0x.win
    annotations:
      cert-manager.io/cluster-issuer: zerossl-prod
      external-dns.alpha.kubernetes.io/target: ip.nidr0x.win
    path: /grafana
    pathType: Prefix
    tls:
      - hosts:
          - monitoring.nidr0x.win
  podSecurityContext:
    fsGroup: 2002
    runAsGroup: 2002
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    runAsGroup: 2002
    runAsNonRoot: true
    runAsUser: 1001
  deploymentStrategy:
    type: Recreate
  fullnameOverride: "victoriametrics-grafana"
  additionalDataSources:
    - name: TeslaMate
      type: postgres
      url: teslamate-database-rw.teslamate.svc.cluster.local
      database: teslamate
      user: postgres
      secureJsonData:
        password: $__env{TESLAMATE_POSTGRESQL_PASSWORD}
      jsonData:
        sslmode: "disable"
        postgresVersion: 1000
      editable: true
      isDefault: false
    - name: VictoriaLogs
      type: loki
      url: http://victorialogs-server.kube-monitoring.svc.cluster.local:9428
      access: proxy
      jsonData:
        maxLines: 1000
      editable: true
      isDefault: false
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: "tesla"
          folder: "Tesla"
          options:
            path: /var/lib/grafana/dashboards/tesla
        - name: "tesla-internal"
          folder: "Tesla/Internal"
          options:
            path: /var/lib/grafana/dashboards/tesla-internal
  dashboards:
    tesla:
      battery-health:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/battery-health.json
      charge-level:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charge-level.json
      charges:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charges.json
      charging-stats:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/charging-stats.json
      database-info:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/database-info.json
      drive-stats:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/drive-stats.json
      drives:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/drives.json
      efficiency:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/efficiency.json
      locations:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/locations.json
      mileage:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/mileage.json
      overview:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/overview.json
      projected-range:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/projected-range.json
      states:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/states.json
      statistics:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/statistics.json
      timeline:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/timeline.json
      trip:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/trip.json
      updates:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/updates.json
      vampire-drain:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/vampire-drain.json
      visited:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/visited.json
    tesla-internal:
      charge-details:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/internal/charge-details.json
      drive-details:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/internal/drive-details.json
      home:
        url: https://raw.githubusercontent.com/teslamate-org/teslamate/master/grafana/dashboards/internal/home.json
  grafana.ini:
    database:
      type: postgres
      host: $__env{host}:$__env{port}
      name: $__env{dbname}
      user: $__env{username}
      password: $__env{password}
      sslmode: disable
      wal: false
    feature_toggles:
      ssoSettingsApi: true
    server:
      domain: monitoring.nidr0x.win
      root_url: "https://monitoring.nidr0x.win/grafana"
      serve_from_sub_path: true
    users:
      allow_sign_up: false
      auto_assign_org: true
      auto_assign_org_id: 1
      auto_assign_org_role: "Viewer"
    auth:
      disable_login_form: true
    security:
      angular_support_enabled: false
      disable_initial_admin_creation: false
      login_attempt_limit: 0
      login_maximum_inactive_lifetime_days: 7
    auth.google:
      enabled: true
      allow_sign_up: true
      auto_login: true
      client_id: $__env{GF_AUTH_GOOGLE_CLIENT_ID}
      client_secret: $__env{GF_AUTH_GOOGLE_CLIENT_SECRET}
      scopes: openid email profile
      auth_url: https://accounts.google.com/o/oauth2/v2/auth
      token_url: https://oauth2.googleapis.com/token
      api_url: https://openidconnect.googleapis.com/v1/userinfo
      allowed_domains: gmail.com
      use_pkce: true
      role_attribute_path: email == 'nidr0x@gmail.com' && 'Admin' || 'None'
      allow_assign_grafana_admin: true
      skip_org_role_sync: false

vmagent:
  enabled: true
  persistentVolume:
    storageClass: proxmox-k8s-zfs
    size: 10Gi

vmsingle:
  enabled: true
  spec:
    storage:
      storageClassName: "proxmox-k8s-zfs"
      resources:
        requests:
          storage: 2Gi
  ingress:
    enabled: false

vmalert:
  enabled: true
  persistentVolume:
    storageClass: proxmox-k8s-zfs
    size: 1Gi

alertmanager:
  enabled: true

# Enable default dashboards (including vmstat)
dashboard:
  enabled: true

# Enable node exporter, kube-state-metrics, etc.
nodeExporter:
  enabled: true
kubeStateMetrics:
  enabled: true

kubelet:
  enabled: true
  vmScrape:
    spec:
      metricRelabelConfigs:
        - action: labeldrop
          regex: (uid)
        - action: labeldrop
          regex: (id|name)
        - action: labeldrop
          regex: "extensions_talos_dev_.*"
        - action: labeldrop

kubeApiserver:
  enabled: true

defaultDashboardsEnabled: true
experimentalDashboardsEnabled: true
