apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: bitwarden

  data:
    - secretKey: emailUser
      remoteRef:
        key: BITWARDEN_SMTP_EMAIL_USER
    - secretKey: emailPassword
      remoteRef:
        key: BITWARDEN_SMTP_EMAIL_PASSWORD
    - secretKey: PING_URL
      remoteRef:
        key: VAULTWARDEN_PING_BACKUP_URL
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: BITWARDEN_ADMIN_TOKEN
    - secretKey: MARIADB_DB_PASSWORD
      remoteRef:
        key: BITWARDEN_MARIADB_DB_PASSWORD
