apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: commafeed-database
  namespace: commafeed
spec:
  env:
    - name: TZ
      value: UTC
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  postgresql:
    parameters:
      max_wal_size: "1GB"
      min_wal_size: "80MB"
      archive_mode: "on"
      wal_keep_size: "640MB"
  bootstrap:
    initdb:
      database: commafeed
      owner: commafeed
  logLevel: info
  backup:
    barmanObjectStore:
      destinationPath: s3://nidr0x-homelab-backups/cloudnative-pg
      endpointURL: https://de6356c843cfe00a0c3ff3b669892ca9.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: commafeed
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: commafeed
          key: SECRET_ACCESS_KEY
      data:
        compression: bzip2
        encryption: AES256
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
    retentionPolicy: "10d"
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: proxmox-k8s-zfs
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "768Mi"

---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: commafeed
  namespace: commafeed
spec:
  cluster:
    name: commafeed-database

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: commafeed-backup
  namespace: commafeed
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: commafeed-database
