k8sServiceHost: localhost
k8sServicePort: 7445

ipv6:
  enabled: true
  nodePort:
    enabled: true
  address: "fd00:10:244::1/64"

ipv4:
  enabled: true
  nodePort:
    enabled: true

ipam:
  mode: "kubernetes"
  ipv6:
    enabled: true
    requestIPv6: true
  ipv4:
    enabled: true
    requestIPv4: true

kubeProxyReplacement: true

# Enable IPv6 for Cilium's internal components
bpf:
  l3:
    enabled: true
    ipv6:
      enabled: true
    ipv4:
      enabled: true

# Enable IPv6 for policy enforcement
policy:
  enforcement:
    ipv6:
      enabled: true
    ipv4:
      enabled: true

# Enable IPv6 for health checks
health:
  enabled: true
  ipv6:
    enabled: true
  ipv4:
    enabled: true

kubeProxyReplacement: true

ipam:
  mode: kubernetes

l2announcements:
  enabled: true

k8sClientRateLimit:
  qps: 50
  burst: 200

enableCiliumEndpointSlice: true

externalIPs:
  enabled: true

operator:
  replicas: 3
  rollOutPods: true

rollOutCiliumPods: true

securityContext:
  capabilities:
    ciliumAgent:
      [
        CHOWN,
        KILL,
        NET_ADMIN,
        NET_RAW,
        IPC_LOCK,
        SYS_ADMIN,
        SYS_RESOURCE,
        DAC_OVERRIDE,
        FOWNER,
        SETGID,
        SETUID,
      ]
    cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

prometheus:
  enabled: false

envoy:
  securityContext:
    capabilities:
      keepCapNetBindService: true
      envoy: [NET_ADMIN, PERFMON, BPF]

authentication:
  enabled: false

debug:
  enabled: false

ingressController:
  enabled: true
  default: true
  loadbalancerMode: shared
  defaultSecretNamespace: cert-manager
  defaultSecretName: prod-cert-zerossl
  service:
    loadBalancerIP: 192.168.1.220
    insecureNodePort: 32434
    secureNodePort: 31247
