apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-database
  namespace: kube-monitoring
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.2

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
  backup:
    barmanObjectStore:
      destinationPath: s3://nidr0x-homelab-backups/cloudnative-pg
      endpointURL: https://de6356c843cfe00a0c3ff3b669892ca9.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: kubepromstack-oauth2
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: kubepromstack-oauth2
          key: SECRET_ACCESS_KEY
      data:
        compression: bzip2
        encryption: AES256
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: AES256
    retentionPolicy: "10d"
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 512Mi
      storageClassName: openebs-hostpath
  monitoring:
    enablePodMonitor: true
  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"

---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: grafana
  namespace: kube-monitoring
spec:
  cluster:
    name: grafana-database

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: grafana-backup
  namespace: kube-monitoring
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: teslamate
