apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: alertmanager
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/alertmanager
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: prometheus
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/prometheus
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: grafana
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/grafana
