apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kubepromstack-oauth2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: kubepromstack-oauth2

  data:
    - secretKey: GF_AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OAUTH2_CLIENT_SECRET
        metadataPolicy: None
    - secretKey: GF_AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: OAUTH2_CLIENT_ID
        metadataPolicy: None
    - secretKey: GRAFANA_POSTGRESQL_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: GRAFANA_POSTGRESQL_PASSWORD
        metadataPolicy: None
    - secretKey: TESLAMATE_POSTGRESQL_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: TESLAMATE_POSTGRESQL_PASSWORD
        metadataPolicy: None
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
