apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kubepromstack-oauth2
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: kubepromstack-oauth2

  data:
    - secretKey: GF_AUTH_GOOGLE_CLIENT_SECRET
      remoteRef:
        key: OAUTH2_CLIENT_SECRET
    - secretKey: GF_AUTH_GOOGLE_CLIENT_ID
      remoteRef:
        key: OAUTH2_CLIENT_ID
    - secretKey: GRAFANA_POSTGRESQL_PASSWORD
      remoteRef:
        key: GRAFANA_POSTGRESQL_PASSWORD
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
    - secretKey: TESLAMATE_POSTGRESQL_PASSWORD
      remoteRef:
        key: TESLAMATE_POSTGRESQL_PASSWORD
