apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: unbound
spec:
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: unbound
          image: klutchell/unbound:main@sha256:17f4bedf629061cbd90f34683d822c1c000295953daf047a262dbf1493a22528 # renovate: docker=klutchell/unbound
          ports:
            - name: unbound-dns-tcp
              containerPort: 5335
              protocol: TCP
            - name: unbound-dns-udp
              containerPort: 5335
              protocol: UDP
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 192Mi
          volumeMounts:
            - name: config
              mountPath: /etc/unbound/custom.conf.d/unbound.conf
              subPath: unbound.conf
      volumes:
        - name: config
          configMap:
            name: unbound-config
