apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: unbound-config
    namespace: unbound
    files:
      - config/unbound.conf

resources:
  - service.yaml
  - deployment.yaml
