apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: proxmox-csi-plugin
  namespace: kube-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: proxmox-csi-plugin
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        config.yaml: |
          clusters:
            - url: https://192.168.1.11:8006/api2/json
              insecure: true
              token_id: "{{ .PROXMOX_CSI_TOKEN_ID }}"
              token_secret: "{{ .PROXMOX_CSI_TOKEN_SECRET }}"
              region: homelab

  data:
    - secretKey: PROXMOX_CSI_TOKEN_ID
      remoteRef:
        key: PROXMOX_CSI_TOKEN_ID
    - secretKey: PROXMOX_CSI_TOKEN_SECRET
      remoteRef:
        key: PROXMOX_CSI_TOKEN_SECRET
