apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: proxmox-k8s-zfs
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: xfs
  storage: proxmox-k8s-zfs
  cache: writethrough
  ssd: "true"
mountOptions:
  - noatime
provisioner: csi.proxmox.sinextra.dev
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
