createNamespace: true

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: proxmox-k8s-lvm
    cache: writethrough
    storage: local-lvm
    reclaimPolicy: Retain
    fstype: ext4
    ssd: true
    mountOptions:
      - noatime
