createNamespace: true

nodeSelector:
  node-role.kubernetes.io/control-plane: ""
tolerations:
  - key: node-role.kubernetes.io/control-plane
    effect: NoSchedule

storageClass:
  - name: proxmox-k8s-zfs
    storage: k8s-storage
    reclaimPolicy: Retain
    fstype: ext4
    ssd: "true"
    mountOptions:
      - noatime
