apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: homeassistant
configMapGenerator:
  - name: homeassistant-visionos-theme
    files:
      - visionos.yaml=themes/visionos.yaml
      - liquid-glass.yaml=themes/liquid-glass.yaml
      - visionos_default.yaml=packages/visionos_default.yaml
resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - http-route.yaml
  - network-policies.yaml
  - service.yaml
  - pdb.yaml
  - configmap.yaml
