nameOverride: "victorialogs"

server:
  persistentVolume:
    enabled: true
    size: 10Gi
    storageClassName: "proxmox-k8s-zfs"
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "1Gi"
  ingress:
    enabled: true
    hosts:
      - name: monitoring.nidr0x.win
        path:
          - /victorialogs
    pathType: Prefix
    tls:
      - hosts:
          - monitoring.nidr0x.win
vector:
  enabled: true
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 256Mi
