apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguardhome
spec:
  selector:
    matchLabels:
      app: adguardhome
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      volumes:
        - name: tls-cert-secret
          secret:
            secretName: prod-cert-zerossl
        - name: config
          configMap:
            name: adguard-config
        - name: users
          secret:
            secretName: users
        - name: adguardhome-sync
          secret:
            secretName: adguardhome-sync
        - name: config-folder
          emptyDir: {}
        - name: work-folder
          emptyDir: {}
      initContainers:
        - name: copy-base-config-adguardhome
          image: public.ecr.aws/docker/library/busybox:latest
          command:
            [
              "cp",
              "/tmp/AdGuardHome.yaml",
              "/opt/adguardhome/conf/AdGuardHome.yaml",
            ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            - name: config-folder
              mountPath: /opt/adguardhome/conf
        - name: copy-base-config-adguardhome-sync
          image: public.ecr.aws/docker/library/busybox:latest
          command:
            [
              "cp",
              "/tmp/AdGuardHome-sync.yaml",
              "/config/AdGuardHome-sync.yaml",
            ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: adguardhome-sync
              mountPath: /tmp/AdGuardHome-sync.yaml
              subPath: AdGuardHome-sync.yaml
            - name: config-folder
              mountPath: /config
        - name: append-users
          image: busybox
          command:
            [
              "sh",
              "-c",
              "cat /tmp/users.yaml >> /opt/adguardhome/conf/AdGuardHome.yaml",
            ]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: users
              mountPath: /tmp/users.yaml
              subPath: users.yaml
            - name: config-folder
              mountPath: /opt/adguardhome/conf
      containers:
        - name: adguardhome-sync
          image: lscr.io/linuxserver/adguardhome-sync:0.6.14
          env:
            - name: TZ
              value: Europe/Madrid
            - name: CONFIGFILE
              value: /config/AdGuardHome-sync.yaml
            - name: LOG_LEVEL
              value: info
          volumeMounts:
            - name: config-folder
              mountPath: /config
          resources:
            requests:
              memory: 32Mi
              cpu: 30m
            limits:
              memory: 64Mi
        - name: adguardhome
          image: adguard/adguardhome:v0.107.55
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 80m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: https-udp
              containerPort: 443
              protocol: UDP
            - name: admin
              containerPort: 3000
              protocol: TCP
            - name: dns-over-tls
              containerPort: 853
              protocol: TCP
            - name: dns-over-quic-1
              containerPort: 784
              protocol: UDP
            - name: dns-over-quic-2
              containerPort: 853
              protocol: UDP
            - name: dns-over-quic-3
              containerPort: 8853
              protocol: UDP
            - name: dnscrypt
              containerPort: 5443
              protocol: TCP
            - name: dnscrypt-udp
              containerPort: 5443
              protocol: UDP
          volumeMounts:
            - name: tls-cert-secret
              mountPath: /certs
            - name: config-folder
              mountPath: /opt/adguardhome/conf
            - name: work-folder
              mountPath: /opt/adguardhome/work
