apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: adguardhome

configMapGenerator:
  - name: adguard-config
    files:
      - config/AdGuardHome.yaml

resources:
  - deployment.yaml
  - ingress.yaml
  - service.yaml
  - secret.yaml
  - pdb.yaml
