apiVersion: v1
kind: PersistentVolume
metadata:
  name: adguardhome-pv-data
  labels:
    app: adguardhome
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: adguardhome-data # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/adguard
