apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguardhome-pvc-data
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      app: adguardhome
