apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: users
  namespace: adguardhome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: users

  data:
    - secretKey: users.yaml
      remoteRef:
        key: ADGUARDHOME_USERS
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguardhome-sync
  namespace: adguardhome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: adguardhome-sync

  data:
    - secretKey: AdGuardHome-sync.yaml
      remoteRef:
        key: ADGUARDHOME_SYNC
