apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users
  namespace: adguardhome
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: users

  data:
    - secretKey: users.yaml
      remoteRef:
        key: ADGUARDHOME_USERS
