apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "tunnel-credentials"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: tunnel-credentials

  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: CF_CREDENTIALS_JSON
