apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: everest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Everest
  destinations:
    - namespace: "*"
      name: "*"
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://github.com/nidr0x/homelab
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
