apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-setup
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argocd/setup/
    repoURL: https://github.com/nidr0x/homelab
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

