apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: everest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Project for Everest
  destinations:
    - namespace: adguardhome
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: cloudnative-pg
      server: https://kubernetes.default.svc
    - namespace: csi-driver-nfs
      server: https://kubernetes.default.svc
    - namespace: gateway
      server: https://kubernetes.default.svc
    - namespace: homeassistant
      server: https://kubernetes.default.svc
    - namespace: homebridge
      server: https://kubernetes.default.svc
    - namespace: kube-monitoring
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: kyverno
      server: https://kubernetes.default.svc
    - namespace: miniflux
      server: https://kubernetes.default.svc
    - namespace: n8n
      server: https://kubernetes.default.svc
    - namespace: talos-backup
      server: https://kubernetes.default.svc
    - namespace: teslamate
      server: https://kubernetes.default.svc
    - namespace: transmission
      server: https://kubernetes.default.svc
    - namespace: wallos
      server: https://kubernetes.default.svc
  sourceRepos:
    - https://community-charts.github.io/helm-charts
    - https://github.com/cert-manager/cert-manager.git
    - https://github.com/nidr0x/k8s-gitops
    - https://cloudnative-pg.github.io/charts
    - https://helm.cilium.io
    - https://charts.jetstack.io
    - https://charts.external-secrets.io
    - https://kubernetes-sigs.github.io/external-dns/
    - https://kubernetes-sigs.github.io/metrics-server/
    - https://kyverno.github.io/kyverno/
    - https://victoriametrics.github.io/helm-charts
    - https://raw.githubusercontent.com/kubernetes-csi/csi-driver-nfs/master/charts
    - ghcr.io/sergelogvinov/charts
    - https://github.com/kubernetes-sigs/gateway-api.git
    - https://stakater.github.io/stakater-charts
    - https://github.com/alex1989hu/kubelet-serving-cert-approver.git
    - ghcr.io/spegel-org/helm-charts
    - https://raw.githubusercontent.com/deliveryhero/helm-charts/refs/heads/master
    - https://charts.deliveryhero.io/
    - https://argoproj.github.io/argo-helm
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: ""
      kind: PersistentVolume
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicyBinding
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: apiregistration.k8s.io
      kind: APIService
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: cilium.io
      kind: CiliumL2AnnouncementPolicy
    - group: cilium.io
      kind: CiliumLoadBalancerIPPool
    - group: external-secrets.io
      kind: ClusterSecretStore
    - group: gateway.networking.k8s.io
      kind: GatewayClass
    - group: kyverno.io
      kind: ClusterPolicy
    - group: networking.k8s.io
      kind: IngressClass
    - group: policies.kyverno.io
      kind: ValidatingPolicy
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: storage.k8s.io
      kind: CSIDriver
    - group: storage.k8s.io
      kind: StorageClass
