apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "{{ .Values.cluster.name }}-argocd-apps-yaml"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: argocd/apps/
    repoURL: https://github.com/nidr0x/k8s-gitops
    targetRevision: "{{ .Values.targetRevision }}"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
