apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd-apps-yaml
spec:
  generators:
    - list:
        elements:
          - name: adguard
          - name: cert-manager
          - name: cilium
          - name: cloudflare-ddns
          - name: csi-driver-nfs
          - name: external-dns
          - name: external-secrets
          - name: freshrss
          - name: gphotos-sync
          - name: homeassistant
          - name: kube-prometheus-stack
          - name: node-problem-detector
          - name: secret-reloader
          - name: teslamate
          - name: transmission
          - name: uptime-kuma
          - name: vaultwarden
  template:
    metadata:
      name: "{{name}}"
    spec:
      project: everest
      source:
        repoURL: https://github.com/nidr0x/k8s-gitops
        path: argocd/apps/{{name}}.yaml
        targetRevision: master
      destination:
        namespace: "{{name}}"
        server: https://kubernetes.default.svc
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
