fullnameOverride: argocd

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 85
    targetMemoryUtilizationPercentage: 85

server:
  ingress:
    enabled: true
    https: false
    ingressClassName: "cilium"
    annotations:
      cert-manager.io/cluster-issuer: zerossl-prod
      external-dns.alpha.kubernetes.io/target: 9a0ffdc6-2725-4fbc-bf4b-e137a7081be3.cfargotunnel.com
    hostname: argocd.nidr0x.win
    extraTls:
      - hosts:
          - argocd.nidr0x.win
  service:
    type: LoadBalancer

  autoscaling:
    enabled: true
    minReplicas: 2
    targetCPUUtilizationPercentage: 65
    targetMemoryUtilizationPercentage: 65

global:
  domain: argocd.nidr0x.win

configs:
  params:
    server.insecure: true
  rbac:
    policy.default: ""
    scopes: "[email, group]"
    policy.csv: |
      g, nidr0x@gmail.com, role:admin
  cm:
    admin.enabled: false
    url: https://argocd.nidr0x.win
    statusbadge.enabled: false
    resource.exclusions: |
      - apiGroups:
          - cilium.io
        kinds:
          - CiliumIdentity
        clusters:
          - "*"
    dex.config: |
      connectors:
        - type: oidc
          id: google
          name: Google
          config:
            issuer: https://accounts.google.com
            clientID: $sso:dex.google.clientID
            clientSecret: $sso:dex.google.clientSecret

    # Adding Applications health check
    resource.customizations.health.argoproj.io_Application: |
      hs = {}
      hs.status = "Progressing"
      hs.message = ""
      if obj.status ~= nil then
        if obj.status.health ~= nil then
          hs.status = obj.status.health.status
          if obj.status.health.message ~= nil then
            hs.message = obj.status.health.message
          end
        end
      end
      return hs
