tunnel: Everest
credentials-file: /etc/cloudflared/credentials/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

warp-routing:
  enabled: true

ingress:
  - hostname: "*.nidr0x.win"
    service: "http://cilium-ingress.kube-system.svc.cluster.local:80"
    originRequest:
      originServerName: "*.nidr0x.win"
  - hostname: "nidr0x.win"
    service: "http://cilium-ingress.kube-system.svc.cluster.local:80"
    originRequest:
      originServerName: "nidr0x.win"
  - service: http_status:404
