apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "tunnel-credentials"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: tunnel-credentials

  data:
    - secretKey: tunnel-credentials
      remoteRef:
        key: CF_TUNNEL_TOKEN
