cloudflare:
  tunnelName: "everest"
  tunnelId: "4460ad72-d81c-445c-9db3-de9ea182a364"
  secretName: "tunnel-credentials"
  ingress:
    - hostname: "*.nidr0x.win"
      service: "https://cilium-ingress.kube-system.svc.cluster.local:443"
      originRequest:
        noTLSVerify: true

resources:
  limits:
    memory: "64Mi"
  requests:
    cpu: "100m"
    memory: "128Mi"

replicaCount: 1
