apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: freekiosk-mqtt
spec:
  refreshPolicy: CreatedOnce
  target:
    name: freekiosk-mqtt
    creationPolicy: Owner
    template:
      type: Opaque
      mergePolicy: Merge
      data:
        username: freekiosk-tablet
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: freekiosk-mqtt-password
