apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teslamate
resources:
  - service.yaml
  - mqtt-password-generator.yaml
  - mqtt-secret.yaml
  - freekiosk-mqtt-password-generator.yaml
  - freekiosk-mqtt-secret.yaml
  - mqtt-configmap.yaml
  - mqtt-acl-configmap.yaml
  - mqtt-pvc.yaml
  - mqtt-service.yaml
  - mqtt-deployment.yaml
  - http-route.yaml
  - network-policies.yaml
  - secret.yaml
  - deployment.yaml
  - database.yaml
  - pdb.yaml
