apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: teslamate
resources:
  - service.yaml
  - http-route.yaml
  - network-policies.yaml
  - secret.yaml
  - deployment.yaml
  - database.yaml
  - pdb.yaml
