apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: teslamate-mqtt
spec:
  refreshInterval: 1h
  target:
    name: teslamate-mqtt
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        username: teslamate
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: teslamate-mqtt-password
