apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: teslamate-mqtt-password
spec:
  allowRepeat: false
  encoding: hex
  length: 32
  noUpper: false
  secretKeys:
    - password
