apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: teslamate

  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: TESLAMATE_ENCRYPTION_KEY
    - secretKey: DATABASE_PASS
      remoteRef:
        key: TESLAMATE_POSTGRESQL_PASSWORD
