apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teslamate
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "kube-monitoring"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: teslamate

  data:
    - secretKey: ENCRYPTION_KEY
      remoteRef:
        key: TESLAMATE_ENCRYPTION_KEY
    - secretKey: DATABASE_PASS
      remoteRef:
        key: TESLAMATE_POSTGRESQL_PASSWORD
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
