apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-rbd-external
provisioner: rbd.csi.ceph.com
parameters:
  clusterID: "ed613c65-ddc2-42e7-b017-24386071e99a"
  pool: ceph-pool-rbd
  imageFeatures: layering
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - discard
