apiVersion: v1
kind: PersistentVolume
metadata:
  name: gphotos-sync-secret-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: gphotos-sync-secret
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/gphotos-sync/secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gphotos-sync-data-pv
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: gphotos-sync-data # make sure it's a unique id in the cluster
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/gphotos-sync
