apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: node-local-dns
  namespace: kube-monitoring
spec:
  endpoints:
    - port: metrics
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      app.kubernetes.io/instance: node-local-dns
      app.kubernetes.io/name: node-local-dns
