apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
spec:
  destination:
    namespace: kube-monitoring
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/monitoring/alloy/
    - repoURL: https://grafana.github.io/helm-charts
      targetRevision: 0.12.5
      chart: alloy
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/monitoring/alloy/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
