apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/ceph-csi-rbd/
    - repoURL: https://ceph.github.io/csi-charts
      targetRevision: 3.2.1
      chart: ceph-csi-rbd
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/ceph-csi-rbd/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
