apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-crds
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: everest
  source:
    repoURL: https://github.com/cert-manager/cert-manager.git
    targetRevision: v1.20.0
    path: deploy/crds
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: false
      selfHeal: true
