apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/cert-manager/
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.19.3
      chart: cert-manager
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/cert-manager/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      prune: false
      selfHeal: false
  ignoreDifferences:
    - group: cert-manager.io
      kind: Certificate
      jsonPointers:
        - /status
    - group: ""
      kind: Secret
      name: cert-manager-webhook-ca
      namespace: cert-manager
      jsonPointers:
        - /data
