apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  destination:
    namespace: cloudnative-pg
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/cloudnative-pg
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.0
      chart: cloudnative-pg
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/cloudnative-pg/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
