apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/cloudflared/
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
