apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      path: external-secrets/
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.10.3
      chart: external-secrets
      helm:
        valueFiles:
          - $nidr0x-homelab/external-secrets/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
