apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/external-secrets/
    - repoURL: https://charts.external-secrets.io
      targetRevision: 0.15.1
      chart: external-secrets
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/external-secrets/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
