apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      path: external-dns/
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.15.0
      chart: external-dns
      helm:
        valueFiles:
          - $nidr0x-homelab/external-dns/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
