apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/external-dns/
    - repoURL: https://kubernetes-sigs.github.io/external-dns/
      targetRevision: 1.16.1
      chart: external-dns
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/external-dns/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
