apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gphotos-sync
spec:
  destination:
    namespace: gphotos-sync
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: gphotos-sync/
    repoURL: https://github.com/nidr0x/k8s-gitops
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
