apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: miniflux
    server: https://kubernetes.default.svc
  project: everest
  source:
    path: kubernetes/main/apps/miniflux/
    repoURL: https://github.com/nidr0x/k8s-gitops
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
