apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-problem-detector
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/monitoring/node-problem-detector/
    - repoURL: https://charts.deliveryhero.io/
      targetRevision: 2.3.14
      chart: node-problem-detector
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/monitoring/node-problem-detector/values.yaml
  syncPolicy:
    syncOptions:
      - Replace=True
    automated:
      prune: true
      selfHeal: true
