apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: proxmox-csi-plugin
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/proxmox-csi-plugin/
    - repoURL: ghcr.io/sergelogvinov/charts
      targetRevision: 0.3.11
      chart: proxmox-csi-plugin
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/proxmox-csi-plugin/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
