apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/openebs
    - repoURL: https://emberstack.github.io/helm-charts
      targetRevision: 9.0.313
      chart: reflector
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/kubernetes-reflector/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
