apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-reloader
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/secret-reloader/
    - repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 1.3.0
      chart: reloader
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/secret-reloader/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
