apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-reloader
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      ref: nidr0x-homelab
    - repoURL: https://github.com/nidr0x/homelab
      targetRevision: master
      path: secret-reloader/
    - repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 1.0.103
      chart: reloader
      helm:
        valueFiles:
          - $nidr0x-homelab/secret-reloader/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
