apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/spegel/
    - repoURL: ghcr.io/spegel-org/helm-charts
      targetRevision: 0.2.0
      chart: spegel
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/spegel/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
