apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: everest
  sources:
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      ref: nidr0x-k8s-gitops
    - repoURL: https://github.com/nidr0x/k8s-gitops
      targetRevision: master
      path: kubernetes/main/apps/system-upgrade-controller/
    - repoURL: https://bjw-s-labs.github.io/helm-charts/
      targetRevision: 4.5.0
      chart: app-template
      helm:
        valueFiles:
          - $nidr0x-k8s-gitops/kubernetes/main/apps/system-upgrade-controller/values.yaml
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
