apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: miniflux
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: miniflux

  data:
    - secretKey: ADMIN_USERNAME
      remoteRef:
        key: MINIFLUX_ADMIN_USERNAME
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: MINIFLUX_ADMIN_PASSWORD
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
