apiVersion: apps/v1
kind: Deployment
metadata:
  name: freshrss
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: freshrss
  template:
    metadata:
      labels:
        app: freshrss
    spec:
      containers:
        - name: freshrss
          image: freshrss/freshrss:1.24.3
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              memory: 256Mi
          volumeMounts:
            - name: freshrss-data
              mountPath: /var/www/FreshRSS/data
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: TZ
              value: "Europe/Madrid"
            - name: CRON_MIN
              value: "1,31"
            - name: DB_HOST
              value: "192.168.1.10"
            - name: DB_USER
              value: "freshrss"
            - name: DB_PASSWORD
              value: "kObUIaCzwQDSvln7RTCiZDwA93SyNB0ERG24WF4AEleeTzPppS21qanT6tfmStnl"
          #- name: PUID
          #  value: "950"
          #- name: PGID
          #  value: "950"
      restartPolicy: Always
      volumes:
        - name: freshrss-data
          persistentVolumeClaim:
            claimName: freshrss-data-pvc
