apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-database
  namespace: freshrss
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  logLevel: info

  bootstrap:
    recovery:
      source: freshrss

  externalClusters:
    - name: freshrss
      barmanObjectStore:
        destinationPath: s3://nidr0x-homelab-backups/cloudnative-pg
        endpointURL: https://de6356c843cfe00a0c3ff3b669892ca9.r2.cloudflarestorage.com
        s3Credentials:
          accessKeyId:
            name: bitwarden
            key: ACCESS_KEY_ID
          secretAccessKey:
            name: bitwarden
            key: SECRET_ACCESS_KEY
        wal:
          maxParallel: 8

  primaryUpdateStrategy: unsupervised

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "256Mi"
      cpu: "250m"
    limits:
      memory: "384Mi"
      cpu: "500m"

---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: freshrss-backup
spec:
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: freshrss
