apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-database
  namespace: freshrss
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.6

  backup:
    barmanObjectStore:
      destinationPath: s3://nidr0x-homelab-backups/cloudnative-pg
      endpointURL: https://de6356c843cfe00a0c3ff3b669892ca9.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: freshrss
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: freshrss
          key: SECRET_ACCESS_KEY
      wal:
        compression: gzip
    retentionPolicy: "10d"

  logLevel: info

  primaryUpdateStrategy: unsupervised

  storage:
    pvcTemplate:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: openebs-hostpath

  monitoring:
    enablePodMonitor: true

  resources:
    requests:
      memory: "512Mi"
      cpu: "1"
    limits:
      memory: "1Gi"
      cpu: "2"
