apiVersion: v1
kind: Namespace
metadata:
  name: freshrss
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: freshrss-cnpg-main-pooler-rw
  namespace: freshrss
spec:
  cluster:
    name: freshrss-cnpg-main
  instances: 1
  pgbouncer:
    paused: false
    poolMode: session
  type: rw
status:
  instances: 1
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: freshrss-cnpg-main-pooler-rw
  namespace: freshrss
spec:
  env:
    - name: TZ
      value: Europe/Madrid
  bootstrap:
    initdb:
      dataChecksums: false
      database: freshrss
      encoding: UTF8
      localeCType: C
      localeCollate: C
      owner: freshrss
  logLevel: info
  storage:
    size: 1024Mi
  monitoring:
    disableDefaultQueries: false
    enablePodMonitor: false
---
apiVersion: v1
kind: Service
metadata:
  name: freshrss
  namespace: freshrss
spec:
  allocateLoadBalancerNodePorts: false
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: postgres
      port: 5435
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: freshrss-cnpg-main-pooler-rw
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
      - ip: 192.168.1.10
