apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
  labels:
    app: freshrss
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: proxmox-k8s-zfs
