apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
  labels:
    app: freshrss
spec:
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: proxmox-k8s-zfs
  resources:
    requests:
      storage: 512Mi
