apiVersion: v1
kind: PersistentVolume
metadata:
  name: freshrss-data
  labels:
    app: freshrss
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeHandle: freshrss-data
    volumeAttributes:
      server: 192.168.1.10
      share: /mnt/main/nfs/freshrss
