apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data-pvc
spec:
  storageClassName: proxmox-k8s-zfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
