apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
spec:
  storageClassName: proxmox-k8s-lvm
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
