apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-data
spec:
  storageClassName: proxmox-k8s-zfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Mi
