apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: freshrss

  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: FRESHRSS_POSTGRESQL_DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: FRESHRSS_POSTGRESQL_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: FRESHRSS_POSTGRESQL_PASSWORD
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
