apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitwarden-data-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: /opt/bitwarden
    type: DirectoryOrCreate
