apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitwarden-data-pvc
  annotations:
    volumeType: local
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bitwarden-data-pv
