apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bitwarden
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: bitwarden

  data:
    - secretKey: emailUser
      remoteRef:
        key: BITWARDEN_SMTP_EMAIL_USER
    - secretKey: emailPassword
      remoteRef:
        key: BITWARDEN_SMTP_EMAIL_PASSWORD
    - secretKey: PING_URL
      remoteRef:
        key: VAULTWARDEN_PING_BACKUP_URL
    - secretKey: ADMIN_TOKEN
      remoteRef:
        key: BITWARDEN_ADMIN_TOKEN
    - secretKey: BITWARDEN_POSTGRESQL_URL
      remoteRef:
        key: BITWARDEN_POSTGRESQL_URL
    - secretKey: ACCESS_KEY_ID
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_ACCESS_KEY_ID
    - secretKey: SECRET_ACCESS_KEY
      remoteRef:
        key: CLOUDNATIVEPG_BACKUP_SECRET_ACCESS_KEY
