apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: cloudflare-api-token-secret

  data:
    - secretKey: CF_API_TOKEN
      remoteRef:
        key: CF_API_TOKEN
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: zerossl-eab-hmac
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-auth-api

  target:
    name: zerossl-eab-hmac

  data:
    - secretKey: ZEROSSL_EAB_HMAC
      remoteRef:
        key: ZEROSSL_EAB_HMAC
