apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: zerossl-prod
spec:
  acme:
    server: https://acme.zerossl.com/v2/DV90
    externalAccountBinding:
      keyID: vqYxTs3cEHjDSL6gswSpSw
      keySecretRef:
        name: zerossl-eab-hmac
        key: ZEROSSL_EAB_HMAC
      keyAlgorithm: HS256
    privateKeySecretRef:
      name: zerossl-prod
    solvers:
      - dns01:
          cloudflare:
            email: nidr0x@gmail.com
            apiKeySecretRef:
              name: cloudflare-api-token-secret
              key: CF_API_KEY
