---
name: gitleaks

on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  push:
    paths-ignore:
      - "**/*.md"
      - "docs/**"
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: gitleaks-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@e0c47f4f8be36e29cdc102c57e68cb5cbf0e8d1e # v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
